### ISSUE TITLE
bug: YouTube Shorts Comment Section

### ISSUE THREAD

**Issue by george-emerald** [ReVanced/revanced-patches-template#1011] opened 2022-11-09 12:44 UTC
### Type

Error at runtime

### Bug description

There's a bug in the application where the Dark theme is misapplied on YouTube Shorts comment sections. When you try to type out a comment, the box where you type is all white, white buttons, white field, white letters, making it incomprehensible. 

### Steps to reproduce

1. Open any short.
2. Type out a comment. 

### Relevant log output

```shell
No relevant log output.
```

### Screenshots or videos

![Screenshot_20221109-143814](https://user-images.githubusercontent.com/42093089/200833208-5c7028c3-c61a-4c2e-989d-ca80671c5301.png)

### Solution

Replace the box with a dark box with aptly coloured letters so that it's legible. 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by george-emerald** [comment] 2022-11-11 11:27
I __did__ search the existing issues. The issue you're referring to is mistagged and had nor response, so I decided to make this one in hopes that proper tagging (denoting the issue's importance) would get a proper response. This is __not__ a cosmetic issue. It would be if the section I'm referring to was in light mode yet still readable (white field with black font). This is not the case. The dark theme is misapplied making it unreadable and unusable thus making this a bug that needs to be addressed.

**Comment by oSumAtrIX** [comment] 2022-11-11 11:30
Dupe of #922.

**Comment by george-emerald** [comment] 2022-11-11 11:32
You closed this as not planned and haven't addressed the issue you're referring to. Does that mean you don't consider it an issue? A simple commit should be able to fix this.

**Comment by oSumAtrIX** [comment] 2022-11-11 11:35
As previously said, it is closed because it is a duplicate.
![Screenshot_2022-11-11-12-34-12-96_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/13122796/201332269-b6a9415b-46eb-4d85-a0d4-f7149301e261.jpg)

If a simple commit should fix this, go ahead and make one instead of creating a duplicate issue and then denying it.

**Closed** 2023-12-16 23:26 UTC
Labels: Bug report
